spring:
  datasource:
    url: jdbc:sqlserver://toshisqlserver.database.windows.net:1433;database=toshisqldb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: toshiadmin
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect



server:
  port: 8082


